### ISSUE TITLE
Shape Key Export Fails on Blender 2.8

### ISSUE THREAD

**Issue by MBetters** [godotengine/collada-exporter#117] opened 2020-01-01 15:00 UTC
I'm using https://github.com/HungryProton/collada-exporter-2.8. I'll try using this repo directly and report back here soon.

**OS:** WIN

**Godot version:** v3.1.2.stable.official

**Blender version:** 2.81a

**Issue description:** Exporting with shape keys results in this error stacktrace:
![BetterColladaExporterShapeKeyError](https://user-images.githubusercontent.com/12706574/71642629-3382d300-2c7c-11ea-86e6-324f44f96247.PNG)

I tried performing the export with and without selecting various objects. Same stacktrace no matter what selection I make.

**Minimal reproduction project:** 
[Player.zip](https://github.com/godotengine/godot-blender-exporter/files/4014167/Player.zip)

The shape key I'd like to export into Godot is called `Skinny` and it belongs to `Armature/Player` in the `Player.blend` I attached.

**Comment by Janders1800** [comment] 2020-04-29 23:54
Can confirm with blender 2.82, Shape Keys don't work, everything else works OK.
Using this fork: https://github.com/jitspoe/collada-exporter-2.8

**Comment by Calinou** [comment] 2022-03-17 21:59
@MBetters @Janders1800 This may have been fixed by https://github.com/godotengine/collada-exporter/pull/131, can you test?

**Comment by Calinou** [comment] 2022-05-02 22:13
Closing due to lack of response. Please comment if you can still reproduce this bug.

**Closed by Calinou** 2022-05-02 22:13 UTC
Labels: bug
