### ISSUE TITLE
Can't import addon on blender 2.8

### ISSUE THREAD

**Issue by gevonstria** [godotengine/collada-exporter#112] opened 2019-08-18 16:48 UTC
I can't seem to install this addon on Blender 2.8.

I copied the folder to the scrips/addon folder, and when I try to search it on the addon list on Blender settings, it is not present.

Any ideas?

**Comment by gevonstria** [comment] 2019-08-18 17:19
I got it working by reinstalling blender, but exporting now causes error.
Here is a screenshot of the error:
https://imgur.com/Z2yG1du

I am kind of desperate and really in need of help.

Thanks!

**Comment by Calinou** [comment] 2019-08-18 17:41
This add-on isn't compatible with Blender 2.8, but you can use a fork such as https://github.com/HungryProton/collada-exporter-2.8.

**Comment by gevonstria** [comment] 2019-08-18 19:21
> This add-on isn't compatible with Blender 2.8 yet, but you can use a third-party fork such as https://github.com/HungryProton/collada-exporter-2.8.

Thank You, forgot to include in my first post that I am using collada-exporter-2.8. I fixed the repeating errors, but the depsgraph is still an issue when exporting :(

**Comment by dydokamil** [comment] 2019-08-23 18:48
I tried using that fork too but got this error:

    location: <unknown location>:-1                                                                                                                                                               
    Traceback (most recent call last):                                                                                                                                                              
    File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_dae\__init__.py", 
    line 172, in execute                                                                           return export_dae.save(self, 
    context, **keywords)                                                                                                                                           
    File "C:\Program Files\Blender 
    Foundation\Blender\2.80\scripts\addons\io_scene_dae\export_dae.py", line 2007, in save                                                                           
    exp.export()                                                                                                                                                                                
    File "C:\Program Files\Blender 
    Foundation\Blender\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1917, in export                                                                         
    self.export_scene()                                                                                                                                                                         
    File "C:\Program Files\Blender 
    Foundation\Blender\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1561, in export_scene                                                                   
    self.export_node(obj, 2)                                                                                                                                                                    
    File "C:\Program Files\Blender 
    Foundation\Blender\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1498, in export_node                                                                    
    self.export_mesh_node(node, il)                                                                                                                                                             
    File "C:\Program Files\Blender 
    Foundation\Blender\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1082, in 
    export_mesh_node                                                               meshdata = self.export_mesh(node, 
    armature)                                                                                                                                                 
    File "C:\Program Files\Blender 
    Foundation\Blender\2.80\scripts\addons\io_scene_dae\export_dae.py", line 541, in export_mesh                                                                     
    armature_modifier = armature_modifiers[0]#node.modifiers.get("Armature")                                                                                                                  
    IndexError: list index out of range                                                                                                                                                                                                                                                                                                                                                         
    location: <unknown location>:-1                                                                                                                                                                                                                                                                                                                                                             
    location: <unknown location>:-1 

After adding an armature and trying to export, blender just hangs and crashes.

**Comment by brylie** [comment] 2019-09-03 18:18
I hope the Blender 2.8 --> Godot will be a critical path of support for Godot Engine team, as they are both quintessential free/open source 3D/game development projects :-)

**Comment by onelsonic** [comment] 2019-09-23 07:16
@reduz what is the best way to export a scene from blender 2.8?
Just starting with Godot and it seems the Collada plugin which should be the best option does not work with the redesigned Blender 2.8.
I tried with GLTF but it is still a work in progress at the moment.

**Comment by Calinou** [comment] 2019-09-23 11:32
@onelsonic Try the [godot-blender-exporter](https://github.com/godotengine/godot-blender-exporter) :slightly_smiling_face:

**Comment by onelsonic** [comment] 2019-10-26 23:58
@Calinou I will have a look thank you

**Comment by vintprox** [comment] 2019-12-22 16:19
So... what's about errors? Were they fixed?

**Comment by vintprox** [comment] 2019-12-22 16:24
Oh, I see the fork is just working fine now. ☺ I hope maintainer of main repository will do something to merge efforts, after all beginners may still be confused and find workarounds they could avoid.

**Comment by Calinou** [comment] 2020-02-26 12:55
Duplicate of #96.

**Closed by Calinou** 2020-02-26 12:55 UTC
