### ISSUE TITLE
exporter adds extra keyframes which don't exist in blender 2.79

### ISSUE THREAD

**Issue by soundsbeard** [godotengine/collada-exporter#113] opened 2019-09-03 21:19 UTC
pc specs if needed: https://pastebin.com/vVYLjhDR
blender version: 2.79 (sub 0), branch: master, commit date: 2018-03-22 14:10, hash: f4dc9f9d68b, type: Release

take a look at 2 bones:
upperLidDriver.R
upperLidDriver.L
they don't have a deform option on them

they have same keyframes along the whole animation
https://i.imgur.com/lY4n12P.jpg
but after exporting with 'better collada', converted upperLidDriver.L has numerous extra keyframes, while upperLidDriver.R has clear animation.
you can see, that all bones with .L at the end on their names have different keys than .R ones. 
this causes distortion of the left eye on frame 0 in godot
https://i.imgur.com/dU4NKWQ.jpg

.blend and .dae files are attached
[eyes issue.zip](https://github.com/godotengine/collada-exporter/files/3571671/eyes.issue.zip)

**Comment by Calinou** [comment] 2022-03-17 22:01
@soundsbeard This may have been fixed by https://github.com/godotengine/collada-exporter/pull/131, can you test?

**Comment by Calinou** [comment] 2022-05-02 22:12
Closing due to lack of response. Please comment if you can still reproduce this bug.

**Closed by Calinou** 2022-05-02 22:12 UTC
Labels: bug
