### ISSUE TITLE
IndexError: list index out of range on Blender 2.80

### ISSUE THREAD

**Issue by GoxelBug** [godotengine/collada-exporter#111] opened 2019-08-11 06:18 UTC
![Annotation 2019-08-11 001752](https://user-images.githubusercontent.com/53970451/62830523-7e1c8980-bbcd-11e9-8b46-6a9151d82cde.png)

**Comment by Calinou** [comment] 2020-02-26 12:55
Duplicate of #96.

**Closed by Calinou** 2020-02-26 12:55 UTC
