### ISSUE TITLE
Transparency/alpha isn't exported in 2.8

### ISSUE THREAD

**Issue by unelsson** [godotengine/collada-exporter#122] opened 2020-06-11 19:24 UTC
The transparency/alpha isn't yet exported, but adding something like this to export_dae.py line 387 should help:
```
        if material.blend_method == "CLIP":
            #Something about opacity maybe? Is it <opacity> and values, I don't know of collada...
        if material.blend_method == "BLEND":
            self.writel(S_FX, 5, "<transparency>")
            self.writel(S_FX, 6, "<float>{}</float>".format(material.alpha_threshold))
            self.writel(S_FX, 5, "</transparency>")
```

**Comment by Calinou** [comment] 2020-07-09 08:00
@unelsson Since the upstream version of this add-on doesn't support Blender 2.8, which fork did you use (and which commit were you using at the time of reporting this)?

**Comment by shayneoneill** [comment] 2020-08-02 13:15
Is this plugin still being developed? The 2 years since last commit, multiple unapproved pull requests and incompatibility with current blends feels like this has been abandoned :(

**Comment by Calinou** [comment] 2020-08-02 13:29
@shayneoneill We don't really have anyone to work on the add-on these days. Since glTF 2.0 and the [ESCN exporter](https://github.com/godotengine/godot-blender-exporter) are gaining traction, there's not as much interest in Collada nowadays.

**Comment by unelsson** [comment] 2020-11-12 12:54
> @unelsson Since the upstream version of this add-on doesn't support Blender 2.8, which fork did you use (and which commit were you using at the time of reporting this)?

Can't remember which one, but I used a fork in some of the PRs related to updating Blender to 2.8. Maybe some of ArtellBlender's PR with some custom changes and cherry-picked commits. I need a working collada exporter, preferably Blender 2.8 or 2.9, so I'm using custom commits to make it running.

**Comment by Calinou** [comment] 2022-03-17 22:00
@unelsson This may have been fixed by https://github.com/godotengine/collada-exporter/pull/131, can you test?

**Comment by Calinou** [comment] 2022-05-02 22:12
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Closed by Calinou** 2022-05-02 22:12 UTC
Labels: enhancement
