### ISSUE TITLE
UV texcoords are exported wrong in Blender 2.82

### ISSUE THREAD

**Issue by unelsson** [godotengine/collada-exporter#121] opened 2020-06-11 14:55 UTC
UV textures are not exported correct in Blender 2.82. 

Changing this line to `float_values += " {} {}".format(v.uv[uvi].x, 1 - v.uv[uvi].y)` seems to fix the problem.
https://github.com/godotengine/collada-exporter/blob/9a8fae951fe76209a7bb6c6cbc692478585283b8/io_scene_dae/export_dae.py#L773

Note: To get this running with 2.82 I have added this change while testing this https://github.com/artellblender/collada-exporter-2.8/pull/3

**Comment by unelsson** [comment] 2020-11-22 22:04
I've had successful exports with this change earlier, but testing with Blender 2.83 and 2.9 the change suggested above seems to fail. Needs some more investigation.

**Comment by Calinou** [comment] 2022-03-17 21:59
@unelsson This may have been fixed by https://github.com/godotengine/collada-exporter/pull/131, can you test?

**Comment by Calinou** [comment] 2022-05-02 22:10
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Closed by Calinou** 2022-05-02 22:10 UTC
Labels: bug
