### ISSUE TITLE
Export fails with 2.8 fork

### ISSUE THREAD

**Issue by matthew798** [godotengine/collada-exporter#120] opened 2020-04-13 21:17 UTC
When trying to export only a selected mesh (only a mesh, no bones, nothing) I get:
```
Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/addons/io_scene_dae/__init__.py", line 173, in execute
    return export_dae.save(self, context, **keywords)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_dae/export_dae.py", line 2068, in save
    exp.export()
  File "/usr/share/blender/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1976, in export
    self.export_scene()
  File "/usr/share/blender/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1621, in export_scene
    self.export_node(obj, 2)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1558, in export_node
    self.export_mesh_node(node, il)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1142, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_dae/export_dae.py", line 642, in export_mesh
    mesh.update(calc_edges=False, calc_edges_loose=False, calc_loop_triangles=True)# 2.80
TypeError: Mesh.update(): takes at most 2 arguments, got 3
```

Using https://github.com/artellblender/collada-exporter-2.8

**Comment by Calinou** [comment] 2020-04-14 08:20
Which 2.8 fork are you using? Please link to it.

**Comment by matthew798** [comment] 2020-04-14 10:39
See edit, thanks.

**Comment by Calinou** [comment] 2022-03-17 21:59
@matthew798 This may have been fixed by https://github.com/godotengine/collada-exporter/pull/131, can you test?

**Comment by Calinou** [comment] 2022-05-02 22:11
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Closed by Calinou** 2022-05-02 22:11 UTC
Labels: bug
