### ISSUE TITLE
Better Collada for Blender 2.8  25052019

### ISSUE THREAD

**Issue by davey362** [godotengine/collada-exporter#107] opened 2019-05-25 19:03 UTC
Fails using the 2.8 (blender-2.80.0-git.e1d1899e7290-windows64) addon and also does not export actions or animations for Godot v3.1.1 with 2.79, only the dae file

![bettercollada](https://user-images.githubusercontent.com/51031728/58373679-db3b6400-7f29-11e9-9a9a-d87842d828a6.jpg)

**Comment by micfan** [comment] 2019-06-02 07:56
+1, plugin not work for https://builder.blender.org/download/blender-2.80-079c7f918c81-win64.zip

**Comment by NyxCode** [comment] 2019-06-03 17:26
+1 for https://builder.blender.org/download/blender-2.80-0efe89bdd810-win64.zip

**Comment by JosephCatrambone** [comment] 2019-06-27 20:26
+1 for blender-2.80.0-git.9bae9b634ec6-windows64  

The API has frozen as of May 25th, so it should be fine to continue working now without fear of additional breaks.

**Comment by MeshVoid** [comment] 2019-07-01 12:31
Receiving the same error with today's build (bbb3500c9716-windows64), can't export anything =((.


Traceback (most recent call last):
  File "C:\000_Blender\blender-2.80.0-git.bbb3500c9716-windows64\2.80\scripts\addons\io_scene_dae\__init__.py", line 172, in execute
    return export_dae.save(self, context, **keywords)
  File "C:\000_Blender\blender-2.80.0-git.bbb3500c9716-windows64\2.80\scripts\addons\io_scene_dae\export_dae.py", line 2007, in save
    exp.export()
  File "C:\000_Blender\blender-2.80.0-git.bbb3500c9716-windows64\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1917, in export
    self.export_scene()
  File "C:\000_Blender\blender-2.80.0-git.bbb3500c9716-windows64\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1561, in export_scene
    self.export_node(obj, 2)
  File "C:\000_Blender\blender-2.80.0-git.bbb3500c9716-windows64\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1498, in export_node
    self.export_mesh_node(node, il)
  File "C:\000_Blender\blender-2.80.0-git.bbb3500c9716-windows64\2.80\scripts\addons\io_scene_dae\export_dae.py", line 1082, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "C:\000_Blender\blender-2.80.0-git.bbb3500c9716-windows64\2.80\scripts\addons\io_scene_dae\export_dae.py", line 560, in export_mesh
    mesh = node.to_mesh(bpy.context.depsgraph, apply_modifiers, calc_undeformed=False) 
AttributeError: 'Context' object has no attribute 'depsgraph'

location: <unknown location>:-1

**Comment by ribhav99** [comment] 2019-07-07 20:18
I have the same issue as MeshVoid above

**Comment by HoutarouOreki** [comment] 2019-07-16 16:48
+1 for blender-2.80rc1-linux-glibc217-x86_64

**Comment by gravymond** [comment] 2019-07-23 23:46
+1 for blender-2.80rc1-2, Arch Linux

**Comment by vini-guerrero** [comment] 2019-08-04 02:41
+1 for macOS Mojave 10.14, Blender 2.80 RC1-2

**Comment by Calinou** [comment] 2020-02-26 12:59
Duplicate of #96.

**Closed by Calinou** 2020-02-26 12:59 UTC
